version: "3.2"
services:
  php:
    build: 
      context: .
    image: httpd
    networks:
      - backend
    environment:
      - MYSQL_HOST=my-mysql-app
      - MYSQL_USER=youssef
      - MYSQL_PASSWORD=root
      - MYSQL_DB=boutique
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "30001:80"
    container_name: my-mysql-app
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=youssef
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=boutique
    container_name: moe-mysql-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=moe-mysql-app
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: moe-phpmyadmin-app
networks:
  backend: